/* eslint-disable */
// Auto-generated by generate-enums script on Tue Oct 24 2023 21:49:22 GMT+0700 (GMT+07:00)

enum EAuthTokenRevokeAction {
	Logout = 0,
	Permanent = 1,
	Replaced = 2,
	Support = 3,
	Consume = 4,
	NonRememberedLogout = 5,
	NonRememberedPermanent = 6,
	Automatic = 7
}

export default EAuthTokenRevokeAction;
