/* eslint-disable */
// Auto-generated by generate-enums script on Tue Oct 24 2023 21:49:22 GMT+0700 (GMT+07:00)

enum EAuthTokenState {
	Invalid = 0,
	New = 1,
	Confirmed = 2,
	Issued = 3,
	Denied = 4,
	LoggedOut = 5,
	Consumed = 6,
	Revoked = 99
}

export default EAuthTokenState;
