/* eslint-disable */
// Auto-generated by generate-enums script on Tue Oct 24 2023 21:49:22 GMT+0700 (GMT+07:00)

enum EAuthTokenPlatformType {
	Unknown = 0,
	SteamClient = 1,
	WebBrowser = 2,
	MobileApp = 3
}

export default EAuthTokenPlatformType;
