/* eslint-disable */
// Auto-generated by generate-enums script on Tue Oct 24 2023 21:49:22 GMT+0700 (GMT+07:00)

enum EAuthSessionSecurityHistory {
	Invalid = 0,
	UsedPreviously = 1,
	NoPriorHistory = 2
}

export default EAuthSessionSecurityHistory;
