/* eslint-disable */
// Auto-generated by generate-enums script on Tue Oct 24 2023 21:49:22 GMT+0700 (GMT+07:00)

enum EBanContentCheckResult {
	NotScanned = 0,
	Reset = 1,
	NeedsChecking = 2,
	VeryUnlikely = 5,
	Unlikely = 30,
	Possible = 50,
	Likely = 75,
	VeryLikely = 100
}

export default EBanContentCheckResult;
