/* eslint-disable */
// Auto-generated by generate-enums script on Tue Oct 24 2023 21:49:22 GMT+0700 (GMT+07:00)

enum ESessionPersistence {
	Invalid = -1,
	Ephemeral = 0,
	Persistent = 1
}

export default ESessionPersistence;
